services:
  app:
    build: .
    ports:
      - "8002:8002"
    environment:
      - DEBUG=True
      - LOADGEN_INTERVAL=1
      - LOADGEN_URLS=http://app:8002/load/io-bound,http://app:8002/load/cpu-bound,http://app:8002/load/memory-spike,http://app:8002/load/stress/1

  prometheus:
    image: prom/prometheus:v3.13.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:12.4.7
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  loadgen:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - app
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - DEBUG=True