[tox]
envlist = py311, lint

[testenv]
deps =
    -rrequirements/dev.txt
    pytest
    pytest-cov
commands =
    pytest --cov=app --cov-fail-under=80 --cov-report term-missing tests/

[testenv:lint]
deps =
    black
    flake8
    isort
commands =
    black .
    isort .
    flake8 .
    