[tox]
envlist = py311, lint, safety
skipsdist = true

[testenv]
deps =
    -rrequirements/dev.txt
    pytest
    pytest-cov
commands =
    pytest --cov=app --cov=worker --cov-fail-under=80 --cov-report term-missing tests/

[testenv:lint]
deps =
    black
    flake8
    isort
commands =
    black --check .
    isort --check-only .
    flake8 .

[testenv:safety]
deps =
    pip-audit
commands =
    pip-audit -r requirements/base.txt
    pip-audit -r requirements/dev.txt
