[tox]
envlist = py311, lint

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=app tests/

[testenv:lint]
deps =
    black
    flake8
    isort
commands =
    black --check .
    isort --check-only .
    flake8 .
    