package main

import (
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
)

// The three application routes, each asserted on its exact status and
// body the way the Python suite asserts its own. /metrics is covered
// separately: its body is generated by the library and is not this
// service's to pin.
func TestApplicationRoutes(t *testing.T) {
	cases := []struct {
		path string
		body string
	}{
		{"/health", `{"status":"ok"}` + "\n"},
		{"/load/io-bound", `{"message":"I/O-bound task completed"}` + "\n"},
		{
			"/load/cpu-bound",
			`{"message":"CPU-bound task completed","result":2000000000}` + "\n",
		},
	}

	mux := newMux()

	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			// The two load routes cost real time on purpose — one
			// sleeps two seconds, the other spins — so they run
			// alongside each other rather than end to end.
			t.Parallel()

			rec := httptest.NewRecorder()
			mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, tc.path, nil))

			if rec.Code != http.StatusOK {
				t.Errorf("status = %d, want %d", rec.Code, http.StatusOK)
			}
			if got := rec.Body.String(); got != tc.body {
				t.Errorf("body = %q, want %q", got, tc.body)
			}
			if got := rec.Header().Get("Content-Type"); got != "application/json" {
				t.Errorf("Content-Type = %q, want %q", got, "application/json")
			}
		})
	}
}

// /metrics is served by promhttp against the default registry. The
// assertion is that the handler is wired and the registry is not empty,
// not what it contains — the names it exports are recorded in the
// feature's plan.md, measured against the running service rather than
// pinned here.
func TestMetricsResponds(t *testing.T) {
	rec := httptest.NewRecorder()
	newMux().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/metrics", nil))

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", rec.Code, http.StatusOK)
	}
	if body := rec.Body.String(); !strings.Contains(body, "go_goroutines") {
		t.Errorf("body does not carry the default registry's collectors: %q", body)
	}
}

// The request metrics are declared by this service rather than inherited
// from the library, so the middleware that feeds them is worth an
// assertion: an instrumented route must move the counter it names.
func TestInstrumentedRouteCountsRequests(t *testing.T) {
	mux := newMux()
	before := counterValue(t, mux)

	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/health", nil))

	if after := counterValue(t, mux); after != before+1 {
		t.Errorf("http_requests_total = %d after one request, want %d", after, before+1)
	}
}

// counterValue counts the http_requests_total sample lines on /metrics.
// Reading the endpoint rather than the collector keeps the assertion on
// what a scrape would see.
func counterValue(t *testing.T, mux *http.ServeMux) int {
	t.Helper()

	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/metrics", nil))

	total := 0
	for _, line := range strings.Split(rec.Body.String(), "\n") {
		if !strings.HasPrefix(line, "http_requests_total{") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			t.Fatalf("unexpected sample line: %q", line)
		}
		value, err := strconv.ParseFloat(fields[1], 64)
		if err != nil {
			t.Fatalf("parsing %q: %v", fields[1], err)
		}
		total += int(value)
	}
	return total
}
