package main

import (
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"

	"go.opentelemetry.io/otel"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"
	semconv "go.opentelemetry.io/otel/semconv/v1.43.0"
)

// The three application routes, each asserted on its exact status and
// body the way the Python suite asserts its own. /metrics is covered
// separately: its body is generated by the library and is not this
// service's to pin.
func TestApplicationRoutes(t *testing.T) {
	cases := []struct {
		path string
		body string
	}{
		{"/health", `{"status":"ok"}` + "\n"},
		{"/load/io-bound", `{"message":"I/O-bound task completed"}` + "\n"},
		{
			"/load/cpu-bound",
			`{"message":"CPU-bound task completed","result":2000000000}` + "\n",
		},
	}

	mux := newMux()

	for _, tc := range cases {
		t.Run(tc.path, func(t *testing.T) {
			// The two load routes cost real time on purpose — one
			// sleeps two seconds, the other spins — so they run
			// alongside each other rather than end to end.
			t.Parallel()

			rec := httptest.NewRecorder()
			mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, tc.path, nil))

			if rec.Code != http.StatusOK {
				t.Errorf("status = %d, want %d", rec.Code, http.StatusOK)
			}
			if got := rec.Body.String(); got != tc.body {
				t.Errorf("body = %q, want %q", got, tc.body)
			}
			if got := rec.Header().Get("Content-Type"); got != "application/json" {
				t.Errorf("Content-Type = %q, want %q", got, "application/json")
			}
		})
	}
}

// /metrics is served by promhttp against the default registry. The
// assertion is that the handler is wired and the registry is not empty,
// not what it contains — the names it exports are recorded in the
// feature's plan.md, measured against the running service rather than
// pinned here.
func TestMetricsResponds(t *testing.T) {
	rec := httptest.NewRecorder()
	newMux().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/metrics", nil))

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", rec.Code, http.StatusOK)
	}
	if body := rec.Body.String(); !strings.Contains(body, "go_goroutines") {
		t.Errorf("body does not carry the default registry's collectors: %q", body)
	}
}

// The request metrics are declared by this service rather than inherited
// from the library, so the middleware that feeds them is worth an
// assertion: an instrumented route must move the counter it names.
func TestInstrumentedRouteCountsRequests(t *testing.T) {
	mux := newMux()
	before := counterValue(t, mux)

	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/health", nil))

	if after := counterValue(t, mux); after != before+1 {
		t.Errorf("http_requests_total = %d after one request, want %d", after, before+1)
	}
}

// counterValue counts the http_requests_total sample lines on /metrics.
// Reading the endpoint rather than the collector keeps the assertion on
// what a scrape would see.
func counterValue(t *testing.T, mux *http.ServeMux) int {
	t.Helper()

	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/metrics", nil))

	total := 0
	for _, line := range strings.Split(rec.Body.String(), "\n") {
		if !strings.HasPrefix(line, "http_requests_total{") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			t.Fatalf("unexpected sample line: %q", line)
		}
		value, err := strconv.ParseFloat(fields[1], 64)
		if err != nil {
			t.Fatalf("parsing %q: %v", fields[1], err)
		}
		total += int(value)
	}
	return total
}

// The path no route claims. Two assertions, and the second is the one
// that would fail silently: registering the catch-all as "/" must not
// take /metrics with it, and a swallowed scrape is a target at up=0
// rather than a test failure.
func TestUnmatchedPathIsAnsweredAndCounted(t *testing.T) {
	mux := newMux()
	before := counterValue(t, mux)

	rec := httptest.NewRecorder()
	mux.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/no-such-path", nil))

	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d", rec.Code, http.StatusNotFound)
	}
	if got, want := rec.Body.String(), `{"detail":"Not Found"}`+"\n"; got != want {
		t.Errorf("body = %q, want %q", got, want)
	}
	if after := counterValue(t, mux); after != before+1 {
		t.Errorf("http_requests_total = %d after one 404, want %d", after, before+1)
	}
}

// Every unknown path reports under one route value, so a scan of the
// address space costs one series rather than one per path.
//
// Asserted on the span, not on /metrics, and the difference is the whole
// point: this service's counter carries no route label at all, so a
// catch-all labelled by the raw path moves no series here and the
// metrics-side assertion passes while the leak is real. What carries the
// value is `http.route`, which is what the derived request metrics are
// built from.
func TestUnmatchedPathsShareOneRouteValue(t *testing.T) {
	spans := recordSpans(t)

	mux := newMux()
	for _, path := range []string{"/one", "/two", "/three"} {
		mux.ServeHTTP(httptest.NewRecorder(), httptest.NewRequest(http.MethodGet, path, nil))
	}

	routes := map[string]int{}
	for _, span := range spans.GetSpans() {
		for _, attr := range span.Attributes {
			if attr.Key == semconv.HTTPRouteKey {
				routes[attr.Value.AsString()]++
			}
		}
	}
	if len(routes) != 1 || routes["unmatched"] != 3 {
		t.Errorf("route values = %v, want three spans under one \"unmatched\"", routes)
	}
}

// recordSpans swaps the global tracer provider for one that keeps every
// span in memory, and puts the previous one back when the test ends.
func recordSpans(t *testing.T) *tracetest.InMemoryExporter {
	t.Helper()

	exporter := tracetest.NewInMemoryExporter()
	previous := otel.GetTracerProvider()
	otel.SetTracerProvider(sdktrace.NewTracerProvider(sdktrace.WithSyncer(exporter)))
	t.Cleanup(func() { otel.SetTracerProvider(previous) })
	return exporter
}

// The chain hop is the one route that calls out, so it is asserted
// against a stub rather than against the real neighbour: what matters
// here is that this service wraps the answer it got, and reports a
// downstream failure as one rather than as its own.
func TestChainWrapsWhatTheNextServiceAnswered(t *testing.T) {
	next := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, `{"service":"service-node"}`)
	}))
	defer next.Close()

	restore := nextChain
	nextChain = next.URL
	defer func() { nextChain = restore }()

	rec := httptest.NewRecorder()
	newMux().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/chain", nil))

	want := `{"service":"service-go","next":{"service":"service-node"}}` + "\n"
	if rec.Code != http.StatusOK {
		t.Errorf("status = %d, want %d", rec.Code, http.StatusOK)
	}
	if got := rec.Body.String(); got != want {
		t.Errorf("body = %q, want %q", got, want)
	}
}

func TestChainReportsADownstreamFailureAsAGatewayError(t *testing.T) {
	next := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer next.Close()

	restore := nextChain
	nextChain = next.URL
	defer func() { nextChain = restore }()

	rec := httptest.NewRecorder()
	newMux().ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/chain", nil))

	if rec.Code != http.StatusBadGateway {
		t.Errorf("status = %d, want %d", rec.Code, http.StatusBadGateway)
	}
	if got := rec.Body.String(); !strings.Contains(got, "500") {
		t.Errorf("body does not name the downstream status: %q", got)
	}
}
