import assert from "node:assert/strict";
import { after, before, describe, test } from "node:test";

import { createServer, routeFor } from "./main.js";

let server;
let origin;

before(async () => {
  server = createServer();
  // Port 0 lets the OS pick, so the suite never collides with a running
  // stack on 8004.
  await new Promise((resolve) => server.listen(0, resolve));
  origin = `http://127.0.0.1:${server.address().port}`;
});

after(() => server.close());

// The three application routes, each asserted on its exact status and
// body the way the Go and Python suites assert their own. /metrics is
// covered separately: its body is generated by the library and is not
// this service's to pin.
describe("application routes", { concurrency: true }, () => {
  const cases = [
    ["/health", '{"status":"ok"}\n'],
    ["/load/io-bound", '{"message":"I/O-bound task completed"}\n'],
    ["/chain", '{"service":"service-node"}\n'],
  ];

  // The two load routes cost real time on purpose — one sleeps two
  // seconds, the other spins — so they run concurrently rather than end
  // to end.
  for (const [path, body] of cases) {
    test(path, async () => {
      const response = await fetch(origin + path);

      assert.equal(response.status, 200);
      assert.equal(response.headers.get("content-type"), "application/json");
      assert.equal(await response.text(), body);
    });
  }

  // The CPU route is asserted on its shape rather than its exact body:
  // the loop runs to a deadline, so the iteration count it reports is a
  // property of the machine and pinning it would fail on a faster one.
  test("/load/cpu-bound", async () => {
    const response = await fetch(origin + "/load/cpu-bound");
    const body = await response.json();

    assert.equal(response.status, 200);
    assert.equal(body.message, "CPU-bound task completed");
    assert.ok(body.result > 0);
  });
});

test("an unknown path answers 404", async () => {
  const response = await fetch(origin + "/nope");

  assert.equal(response.status, 404);
  assert.equal(await response.text(), '{"detail":"Not Found"}\n');
});

// The assertion is that the handler is wired and the default registry is
// not empty, not what it contains — the names this service exports are
// recorded in the feature's plan.md, measured against the running
// service rather than pinned here.
test("/metrics serves the default registry", async () => {
  const response = await fetch(origin + "/metrics");
  const body = await response.text();

  assert.equal(response.status, 200);
  assert.match(body, /process_cpu_seconds_total/);
  assert.match(body, /process_resident_memory_bytes/);
});

// The inverse of the assertion this file used to carry. This service
// named a request `route`/`status_code`/`method`, agreeing with neither
// of the other two, and that disagreement is what the derived metrics
// replaced — so serving a request must now move no request series at
// all. A library left in place but still counting would keep publishing
// the convention.
test("no request series is published", async () => {
  await fetch(origin + "/health");
  await fetch(origin + "/one");

  const body = await fetch(origin + "/metrics").then((r) => r.text());

  assert.ok(!body.includes("http_requests_total"));
  assert.ok(!body.includes("http_request_duration_seconds"));
});

// A path nobody serves must not become a label value of its own: that is
// the cardinality failure this service would otherwise demonstrate the
// wrong way.
//
// Asserted on the span, not on /metrics, because /metrics no longer
// carries a route at all — the value now travels on `http.route`, which
// is what the derived request metrics group by. The tests run without
// the SDK loaded, so the span is read from a provider registered here.
// Asserted on the label rather than on /metrics, because /metrics no
// longer carries a route at all: the value travels on the span, and the
// derived request metrics group by it. Driving the server over HTTP
// cannot see it — the active span inside the handler is the one the HTTP
// instrumentation opens, not one a client-side test can reach.
test("an unmatched path is labelled by one fixed value", () => {
  assert.equal(routeFor("/health"), "/health");
  assert.equal(routeFor("/chain"), "/chain");

  for (const path of ["/one", "/two", "/three"]) {
    assert.equal(routeFor(path), "unmatched");
  }
});

