import assert from "node:assert/strict";
import { after, before, describe, test } from "node:test";

import { trace } from "@opentelemetry/api";
import { logs } from "@opentelemetry/api-logs";
import client from "prom-client";

import { createServer, routeFor } from "./main.js";

// The smallest thing the logs API accepts as a provider, registered
// once: a second setGlobalLoggerProvider is ignored with a warning, so
// registering per test silently leaves every test after the first
// reading an array nothing writes to. The sink is shared and emptied
// instead.
const emitted = [];

logs.setGlobalLoggerProvider({
  getLogger: () => ({ emit: (record) => emitted.push(record) }),
});

function collectRecords() {
  emitted.length = 0;
  return emitted;
}

let server;
let origin;

before(async () => {
  server = createServer();
  // Port 0 lets the OS pick, so the suite never collides with a running
  // stack on 8004.
  await new Promise((resolve) => server.listen(0, resolve));
  origin = `http://127.0.0.1:${server.address().port}`;
});

after(() => server.close());

// The three application routes, each asserted on its exact status and
// body the way the Go and Python suites assert their own. /metrics is
// covered separately: its body is generated by the library and is not
// this service's to pin.
describe("application routes", { concurrency: true }, () => {
  const cases = [
    ["/health", '{"status":"ok"}\n'],
    ["/load/io-bound", '{"message":"I/O-bound task completed"}\n'],
    ["/chain", '{"service":"service-node"}\n'],
  ];

  // The two load routes cost real time on purpose — one sleeps two
  // seconds, the other spins — so they run concurrently rather than end
  // to end.
  for (const [path, body] of cases) {
    test(path, async () => {
      const response = await fetch(origin + path);

      assert.equal(response.status, 200);
      assert.equal(response.headers.get("content-type"), "application/json");
      assert.equal(await response.text(), body);
    });
  }

  // The CPU route is asserted on its shape rather than its exact body:
  // the loop runs to a deadline, so the iteration count it reports is a
  // property of the machine and pinning it would fail on a faster one.
  test("/load/cpu-bound", async () => {
    const response = await fetch(origin + "/load/cpu-bound");
    const body = await response.json();

    assert.equal(response.status, 200);
    assert.equal(body.message, "CPU-bound task completed");
    assert.ok(body.result > 0);
  });
});

test("an unknown path answers 404", async () => {
  const response = await fetch(origin + "/nope");

  assert.equal(response.status, 404);
  assert.equal(await response.text(), '{"detail":"Not Found"}\n');
});

// The assertion is that the handler is wired and the default registry is
// not empty, not what it contains — the names this service exports are
// recorded in the feature's plan.md, measured against the running
// service rather than pinned here.
test("/metrics serves the default registry", async () => {
  const response = await fetch(origin + "/metrics");
  const body = await response.text();

  assert.equal(response.status, 200);
  assert.match(body, /process_cpu_seconds_total/);
  assert.match(body, /process_resident_memory_bytes/);
});

// The inverse of the assertion this file used to carry. This service
// named a request `route`/`status_code`/`method`, agreeing with neither
// of the other two, and that disagreement is what the derived metrics
// replaced — so serving a request must now move no request series at
// all. A library left in place but still counting would keep publishing
// the convention.
test("no request series is published", async () => {
  await fetch(origin + "/health");
  await fetch(origin + "/one");

  const body = await fetch(origin + "/metrics").then((r) => r.text());

  assert.ok(!body.includes("http_requests_total"));
  assert.ok(!body.includes("http_request_duration_seconds"));
});

// A path nobody serves must not become a label value of its own: that is
// the cardinality failure this service would otherwise demonstrate the
// wrong way.
//
// Asserted on the span, not on /metrics, because /metrics no longer
// carries a route at all — the value now travels on `http.route`, which
// is what the derived request metrics group by. The tests run without
// the SDK loaded, so the span is read from a provider registered here.
// Asserted on the label rather than on /metrics, because /metrics no
// longer carries a route at all: the value travels on the span, and the
// derived request metrics group by it. Driving the server over HTTP
// cannot see it — the active span inside the handler is the one the HTTP
// instrumentation opens, not one a client-side test can reach.
test("an unmatched path is labelled by one fixed value", () => {
  assert.equal(routeFor("/health"), "/health");
  assert.equal(routeFor("/chain"), "/chain");

  for (const path of ["/one", "/two", "/three"]) {
    assert.equal(routeFor(path), "unmatched");
  }
});



// The 500 paths, and the line each of them leaves. Neither is reachable
// through a normal request, so each is provoked at the one seam it has:
// the registry that /metrics awaits, and the span lookup every other
// route goes through. Provoking them is the point — without a line
// here, a request that failed is a status and nothing else.
test("a failing registry is reported and logged", async () => {
  const records = collectRecords();
  const restore = client.register.metrics;
  client.register.metrics = async () => {
    throw new Error("collector exploded");
  };

  try {
    const response = await fetch(origin + "/metrics");
    assert.equal(response.status, 500);
  } finally {
    client.register.metrics = restore;
  }

  assert.equal(records.length, 1);
  assert.equal(records[0].severityText, "ERROR");
  assert.equal(records[0].body, "metrics collection failed");
  assert.equal(records[0].attributes["error.type"], "Error");
});

test("a handler that throws is answered and logged", async () => {
  const records = collectRecords();
  const restore = trace.getActiveSpan;
  trace.getActiveSpan = () => {
    throw new Error("boom");
  };

  try {
    const response = await fetch(origin + "/health");
    assert.equal(response.status, 500);
    assert.equal(await response.text(), "Internal Server Error\n");
  } finally {
    trace.getActiveSpan = restore;
  }

  assert.equal(records.length, 1);
  assert.equal(records[0].body, "unhandled exception");
  assert.equal(records[0].attributes["url.path"], "/health");
  assert.equal(records[0].attributes["http.request.method"], "GET");
});


// The recorded debt, this service's third of it. The hook is what keeps
// a scrape every five seconds out of the trace store — and, since the
// request metrics are derived from those spans, out of the throughput
// panel as well. Importing tracing.mjs here starts no SDK: the module
// only assembles one when it is loaded, and the export is a plain
// predicate.
test("the scrape stays out of the traces", async () => {
  const { isScrape } = await import("./tracing.mjs");

  assert.equal(isScrape({ url: "/metrics" }), true);
  // The control: a predicate that returned true for everything would
  // pass the line above and silently trace nothing at all.
  for (const path of ["/health", "/chain", "/load/io-bound", "/metricsss"]) {
    assert.equal(isScrape({ url: path }), false, path);
  }
});
