import assert from "node:assert/strict";
import { after, before, describe, test } from "node:test";

import { createServer } from "./main.js";

let server;
let origin;

before(async () => {
  server = createServer();
  // Port 0 lets the OS pick, so the suite never collides with a running
  // stack on 8004.
  await new Promise((resolve) => server.listen(0, resolve));
  origin = `http://127.0.0.1:${server.address().port}`;
});

after(() => server.close());

// The three application routes, each asserted on its exact status and
// body the way the Go and Python suites assert their own. /metrics is
// covered separately: its body is generated by the library and is not
// this service's to pin.
describe("application routes", { concurrency: true }, () => {
  const cases = [
    ["/health", '{"status":"ok"}\n'],
    ["/load/io-bound", '{"message":"I/O-bound task completed"}\n'],
  ];

  // The two load routes cost real time on purpose — one sleeps two
  // seconds, the other spins — so they run concurrently rather than end
  // to end.
  for (const [path, body] of cases) {
    test(path, async () => {
      const response = await fetch(origin + path);

      assert.equal(response.status, 200);
      assert.equal(response.headers.get("content-type"), "application/json");
      assert.equal(await response.text(), body);
    });
  }

  // The CPU route is asserted on its shape rather than its exact body:
  // the loop runs to a deadline, so the iteration count it reports is a
  // property of the machine and pinning it would fail on a faster one.
  test("/load/cpu-bound", async () => {
    const response = await fetch(origin + "/load/cpu-bound");
    const body = await response.json();

    assert.equal(response.status, 200);
    assert.equal(body.message, "CPU-bound task completed");
    assert.ok(body.result > 0);
  });
});

test("an unknown path answers 404", async () => {
  const response = await fetch(origin + "/nope");

  assert.equal(response.status, 404);
  assert.equal(await response.text(), '{"detail":"Not Found"}\n');
});

// The assertion is that the handler is wired and the default registry is
// not empty, not what it contains — the names this service exports are
// recorded in the feature's plan.md, measured against the running
// service rather than pinned here.
test("/metrics serves the default registry", async () => {
  const response = await fetch(origin + "/metrics");
  const body = await response.text();

  assert.equal(response.status, 200);
  assert.match(body, /process_cpu_seconds_total/);
  assert.match(body, /process_resident_memory_bytes/);
});

// The request metrics are declared by this service rather than inherited
// from the library, so the middleware that feeds them is worth an
// assertion: an instrumented route must move the counter it names.
test("an instrumented route counts the request", async () => {
  const before = await counterTotal();

  await fetch(origin + "/health");

  assert.equal(await counterTotal(), before + 1);
});

// A path nobody serves must not become a label value of its own: that is
// the cardinality failure this service would otherwise demonstrate the
// wrong way.
test("an unmatched path is labelled by one fixed value", async () => {
  await fetch(origin + "/one");
  await fetch(origin + "/two");

  const lines = await sampleLines("http_requests_total");
  const unmatched = lines.filter((line) => line.includes('route="unmatched"'));

  assert.equal(unmatched.length, 1);
  assert.ok(!lines.some((line) => line.includes('route="/one"')));
});

// Reading the endpoint rather than the registry keeps every assertion on
// what a scrape would actually see.
async function sampleLines(metric) {
  const body = await fetch(origin + "/metrics").then((r) => r.text());
  return body
    .split("\n")
    .filter((line) => line.startsWith(`${metric}{`));
}

async function counterTotal() {
  const lines = await sampleLines("http_requests_total");
  return lines.reduce((total, line) => total + Number(line.split(" ").pop()), 0);
}

// A client that hangs up mid-request is exactly the request an
// observability demo must not lose, and listening only for `finish`
// loses it.
test("a request the client abandons is still counted", async () => {
  const before = await counterTotal();
  const controller = new AbortController();

  const abandoned = fetch(origin + "/load/io-bound", {
    signal: controller.signal,
  });
  setTimeout(() => controller.abort(), 100);
  await assert.rejects(abandoned);
  // The server sees the socket close on its own schedule.
  await new Promise((resolve) => setTimeout(resolve, 200));

  assert.equal(await counterTotal(), before + 1);
  const lines = await sampleLines("http_requests_total");
  assert.ok(lines.some((line) => line.includes('status_code="499"')));
});
